version: '3.8'

services:
  employee_service:
    build: '.'
    ports:
      - 8080:8080
  db:
    image: postgres
    environment:
      POSTGRES_USER: HR
      POSTGRES_PASSWORD: HR
      POSTGRES_DB: employeedb
    volumes:
    - ./docker/volumes/postgres:/var/lib/postgresql/data postgres
    ports:
      - 5433:5432
  grafana:
    build: './scripts/config/grafana'
    ports:
      - 3000:3000
    volumes:
      - ./scripts/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./scripts/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./scripts/prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
networks:
  monitoring: